config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  get 'trips' => 'trips#index', as: :user_root
  resources :blog_posts, only: [:index]
  resources :trips do
    resources :expenses do
      resources :debts, only: [:create]
    end
    resources :debts, only: [:index]
    resources :invites, only: [:create]
  end

  resources :cities, only: [:index]
  resources :currencies, only: [:index]

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_and_belongs_to_many :users, autosave: true
  has_many :expenses

  scope :most_recent, -> (qt = 10) { order(start_date: :desc).limit(qt) }

  monetize :exchange_rate_cents, with_model_currency: :currency

  def amount_of_days
    (end_date - start_date + 1).to_i
  end

  def amount_of_days_until_now
    if Date.current > end_date
      amount_of_days
    else
      (Date.current - start_date + 1).to_i
    end
  end

  def local_currency
    Currency.find(currency)
  end

  def current_day_by_user(user)
    sum_expenses(expenses_by_user(user).by_date(Date.current), :amount)
  end

  def current_week_by_user(user)
    expenses = expenses_by_user(user).order(:date)
    return Money.new(0, currency) unless expenses.present?

    week_expenses = expenses.where('date >= ?', Date.today.beginning_of_week)
    sum_expenses(week_expenses, :amount)
  end

  def average_per_day_by_user(user)
    expenses = expenses_by_user(user).order(:date)
    return Money.new(0, currency) unless expenses.present?

    (total_by_user(user) / amount_of_days_until_now)
  end

  def average_per_week_by_user(user)
    average_per_day_by_user(user) * 7
  end

  def expenses_by_user(user)
    expenses.by_user(user)
  end

  def total_by_user(user)
    sum_expenses_by_user_with(user, :amount)
  end

  def paid_for_total_by_user(user)
    sum_expenses_by_user_with(user, :total_debt)
  end

  def total_by_user_in_exchange_currency(user)
    calc_in_exchange_currency(total_by_user(user).cents)
  end

  def paid_for_total_by_user_in_exchange_currency(user)
    calc_in_exchange_currency(paid_for_total_by_user(user).cents)
  end

  def calc_in_exchange_currency(value_in_cents)
    return Money.new(0) if exchange_rate_cents.zero?

    Money.new(total_exchange(value_in_cents), exchange_rate_currency)
  end

  def current?
    (start_date..end_date).cover?(Date.today)
  end

  private

  def total_exchange(value_in_cents)
    value_in_cents * exchange_rate_cents / (local_currency.smallest_denomination*100.00)
  end

  def sum_expenses_by_user_with(user, method)
    sum_expenses(expenses_by_user(user), method)
  end

  def sum_expenses(list, method)
    list.inject(Money.new(0, currency)) { |a, e| a + e.send(method) }
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!

  def index
    @trips = current_user.trips.most_recent(8)
  end

  def create
    trip = current_user.trips.build(trip_params)
    ActiveRecord::Base.transaction do
      current_user.save!
    end

    flash[:notice] = "New trip created successfuly!"
    redirect_to trip
  rescue Exception => e
    flash[:alert] = "Cannot create the trip. Error: #{e.message}!"
    redirect_to trips_path
  end

  def update
    trip = find_trip

    ActiveRecord::Base.transaction do
      trip.update_attributes!(trip_params)
    end

    flash[:notice] = "Trip updated successfuly!"
    redirect_to trip
  rescue Exception => e
    flash[:alert] = "Cannot update the trip. Error: #{e.message}!"
    redirect_to trip
  end

  def show
    @trip = find_trip
    @expenses = @trip.expenses_by_user(current_user).most_recent(20)
  end

  def destroy
    trip = find_trip
    trip.destroy

    flash[:notice] = "Trip deleted!"
    redirect_to trips_path
  end

  private

  def find_trip
    current_user.trips.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:start_date, :end_date, :country, :city,
                                 :currency, :exchange_rate,
                                 :exchange_rate_currency)
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_add_exchange_rate.html.erb
<%= link_to link_name, "#", 'data-toggle'=>'modal', 'data-target'=>'#addExchangeRateModal' %>
<!-- Modal -->
<div class="modal fade" id="addExchangeRateModal" tabindex="-1" role="dialog" aria-labelledby="addExchangeRateModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <%= form_for trip, url: trip_path(trip), method: :patch do |trip_form| %>
        <div class="modal-body text-left">
          <%= trip_form.hidden_field :exchange_rate_currency, value: current_user.currency %>
          <table>
            <tbody>
              <tr>
                <td class="text-right"><%= "#{trip.local_currency.try(:smallest_denomination)} #{trip.currency} =" %></td>
                <td class="col-md-5"><%= trip_form.text_field :exchange_rate, class: "form-control mask-money" %></td>
                <td><%= current_user.currency %></td>
              <tr>
            </tbody>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= trip_form.submit "Done", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/_add_expense.html.erb
<div class="row">
  <%= form_for :expense, url: trip_expenses_path(trip), method: :post do |expense_form| %>
    <%= expense_form.hidden_field :amount_currency, value: trip.currency %>
    <div class="col-md-2">
      <div class="form-group">
        <%= expense_form.label :date %>
        <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></div>
          <%= expense_form.text_field :date, value: l(Date.today), class: "form-control datepicker" %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <%= expense_form.label :amount %>
        <div class="input-group">
          <div class="input-group-addon"><%= trip.local_currency.symbol %></div>
          <%= expense_form.text_field :amount, class: "form-control mask-money" %>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <%= expense_form.label :description %>
        <%= expense_form.text_area :description, class: "form-control", rows: 2 %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="form-group">
        <%= expense_form.label :category %>
        <%= expense_form.collection_select :category_id, current_user.categories, :id, :name, {prompt: 'Select'}, {class: "form-control"} %>
      </div>
    </div>
    <div class="col-md-2">
      <br>
      <%= button_tag(type: 'submit', class: "btn btn-success btn-block") do %>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add expense
      <% end %>
    </div>
  <% end %>
</div>

app/views/trips/_add_paid_for.html.erb
<%= link_to "#", class: 'btn btn-default btn-sm', 'data-toggle'=>'modal', 'data-target'=>"#addPaidToModal_#{expense.id}" do %>
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
  <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <strong>PAID FOR</strong>
<% end %>

<!-- Modal -->
<div class="modal fade" id=<%="addPaidToModal_#{expense.id}"%> tabindex="-1" role="dialog" aria-labelledby="addPaidToModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="addPaidToModalLabel">Paid to</h4>
      </div>
      <div class="modal-body">
        <%= form_for :debt, url: trip_expense_debts_path(trip_id: trip.id, expense_id: expense.id), method: :post do |debt_form| %>
          <div class="row">
            <%= debt_form.hidden_field :recipient_id, value: current_user.id %>
            <div class="form-group col-md-12">
              <%= debt_form.collection_select :user_id, (trip.users - [current_user]), :id, :email, {prompt: 'Select User'}, {id: 'select_user', class: "form-control"} %>
            </div>
            <div class="form-group col-md-12">
              <%= debt_form.label :amount %>
              <div class="input-group">
                <div class="input-group-addon">$</div>
                <%= debt_form.text_field :amount, class: "form-control mask-money" %>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= debt_form.submit "Create", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/_add_paid_to.html.erb
<%= link_to "#", class: 'btn btn-default btn-sm', 'data-toggle'=>'modal', 'data-target'=>"#addPaidToModal_#{expense.id}" do %>
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
<% end %>

<!-- Modal -->
<div class="modal fade" id=<%="addPaidToModal_#{expense.id}"%> tabindex="-1" role="dialog" aria-labelledby="addPaidToModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="addPaidToModalLabel">Paid to</h4>
      </div>
      <div class="modal-body">
        <%= form_for :debt, url: trip_expense_debts_path(trip_id: trip.id, expense_id: expense.id), method: :post do |debt_form| %>
          <div class="row">
            <%= debt_form.hidden_field :recipient_id, value: current_user.id %>
            <div class="form-group col-md-12">
              <%= debt_form.collection_select :user_id, (trip.users - [current_user]), :id, :email, {prompt: 'Select User'}, {id: 'select_user', class: "form-control"} %>
            </div>
            <div class="form-group col-md-12">
              <%= debt_form.label :amount %>
              <div class="input-group">
                <div class="input-group-addon">$</div>
                <%= debt_form.text_field :amount, class: "form-control mask-money" %>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= debt_form.submit "Create", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/_add_trip.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to "#", class: 'btn btn-success', 'data-toggle'=>'modal', 'data-target'=>'#addTripModal' do %>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Trip
    <% end %>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="addTripModal" tabindex="-1" role="dialog" aria-labelledby="addTripModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="addTripModalLabel">New Trip</h4>
      </div>
      <div class="modal-body">
        <%= form_for :trip, url: trips_path, method: :post do |trip_form| %>
          <div class="row">
            <div class="form-group col-md-12">
              <%= trip_form.label :country %>
              <%= trip_form.collection_select :country, countries_available, :name, :name, {prompt: 'Select a country'}, {id: 'select_country', class: "form-control"} %>
            </div>
          </div>
          <div class="row">
            <div class="form-group col-md-12">
              <%= trip_form.label :city %>
              <%= trip_form.select :city, [], {}, {id: "select_city", class: "form-control"} %>
            </div>
          </div>
          <div class="row">
            <div class="form-group col-md-12">
              <%= trip_form.label :currency %>
              <%= trip_form.collection_select :currency, currencies_available, :iso_code, :code_and_name, {prompt: 'Select a currency'}, {id: 'select_currency', class: "form-control"} %>
            </div>
          </div>
          <div class="row">
            <div class="form-group col-md-6">
              <%= trip_form.label :start_date %>
              <%= trip_form.text_field :start_date, value: l(Date.current), class: 'form-control datepicker', id: 'start_date' %>
            </div>
            <div class="form-group col-md-6">
              <%= trip_form.label :end_date %>
              <%= trip_form.text_field :end_date, class: 'form-control datepicker', id: 'end_date' %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= trip_form.submit "Create", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/_edit_expense_modal.html.erb
<div class="modal fade" id=<%="editExpenseModal_#{expense.id}"%> tabindex="-1" role="dialog" aria-labelledby="editExpenseModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="editExpenseModalLabel">Edit expense</h4>
      </div>
      <%= form_for expense, url: trip_expense_path(trip_id: trip.id, id: expense.id), method: :patch do |edit_expense_form| %>
        <div class="modal-body">
          <div class="form-group">
            <%= edit_expense_form.label :date %>
            <div class="input-group">
              <div class="input-group-addon"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></div>
              <%= edit_expense_form.text_field :date, value: l(expense.date), class: "form-control datepicker" %>
            </div>
          </div>
          <div class="form-group">
            <%= edit_expense_form.label :amount %>
            <div class="input-group">
              <div class="input-group-addon">$</div>
              <%= edit_expense_form.text_field :amount, class: "form-control mask-money" %>
            </div>
          </div>
          <div class="form-group">
            <%= edit_expense_form.label :description %>
            <%= edit_expense_form.text_area :description, class: "form-control", rows: 2 %>
          </div>
          <div class="form-group">
            <%= edit_expense_form.label :category %>
            <%= edit_expense_form.collection_select :category_id, current_user.categories, :id, :name, {prompt: 'Select'}, {class: "form-control"} %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= edit_expense_form.submit "Save changes", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/_edit_trip.html.erb
<%= link_to "#", class: 'btn btn-default', 'data-toggle'=>'modal', 'data-target'=>'#editTripModal' do %>
  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
<% end %>

<!-- Modal -->
<div class="modal fade" id="editTripModal" tabindex="-1" role="dialog" aria-labelledby="editTripModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content text-left">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="editTripModalLabel">Edit Trip</h4>
      </div>
      <div class="modal-body">
        <%= form_for trip, url: trip_path(trip), method: :patch do |trip_form| %>
            <div class="row">
              <div class="form-group col-md-12">
                <%= trip_form.label :country %>
                <%= trip_form.text_field :country, class: 'form-control' %>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-12">
                <%= trip_form.label :city %>
                <%= trip_form.text_field :city, class: 'form-control' %>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-12">
                <%= trip_form.label :currency %>
                <%= trip_form.text_field :currency, class: 'form-control' %>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-6">
                <%= trip_form.label :start_date %>
                <%= trip_form.text_field :start_date, class: 'form-control datepicker', id: 'start_date' %>
              </div>
              <div class="form-group col-md-6">
                <%= trip_form.label :end_date %>
                <%= trip_form.text_field :end_date, class: 'form-control datepicker', id: 'end_date' %>
              </div>
            </div>
          </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= trip_form.submit "Save changes", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/_expenses_table.html.erb
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Date</th>
        <th>Amount</th>
        <th>Description</th>
        <th>Category</th>
        <th>Extra</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% expenses.each do |expense| %>
        <tr id="expense#<%= expense.id %>">
          <td><%= l(expense.date) %></td>
          <td><%= expense.amount.format %></td>
          <td><%= expense.description %></td>
          <td><%= expense.category_name %></td>
          <td>
            <table>
              <tbody>
                <tr>
                  <td>
                    <%= render partial: 'debts/add_paid_for', locals: {trip: expense.trip, expense: expense} %>
                  </td>
                  <td>
                    <ul>
                      <% expense.debts.each do |debt| %>
                        <li><%= "#{debt.user.email}: #{expense.total_debt_by_user(debt.user).format}" %></li>
                      <% end %>
                    </ul>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
          <td>
            <%= link_to '#', class:'btn btn-primary btn-sm', 'data-toggle'=>'modal', 'data-target'=> "#editExpenseModal_#{expense.id}" do %>
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
            <% end %>
            <%= render partial: 'edit_expense_modal', locals: {trip: expense.trip, expense: expense} %>
            <%= link_to trip_expense_path(trip_id: trip.id, id: expense.id), method: :delete, data: {confirm: "Are you sure?"}, class:'btn btn-danger btn-sm' do %>
              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete
            <% end %>
          </td>
        </tr>
      <% end %>
        <tr>
          <th></th>
          <th>Total Amount</th>
          <th></th>
          <th></th>
          <th>Total Credit</th>
          <th></th>
        </tr>
        <tr class="warning">
          <td></td>
          <td><%= trip.total_by_user(current_user).format %></td>
          <td></td>
          <td></td>
          <td><%= trip.paid_for_total_by_user(current_user).format %></td>
          <td></td>
        </tr>
        <tr class="info">
          <td></td>
          <td><%= trip.total_by_user_in_exchange_currency(current_user).format %></td>
          <td></td>
          <td></td>
          <td><%= trip.calc_in_exchange_currency(trip.paid_for_total_by_user(current_user).cents).format %></td>
          <td></td>
        </tr>
    </tbody>
  </table>
</div>

app/views/trips/_trip.html.erb
<div class="col-md-3">
  <div class="thumbnail text-center">
    <% if trip.current? %>
      <div class="row pull-right">
        <span class="label label-warning">Current</span>
      </div>
    <% end %>
    <br>
    <div class="row">
      <%= link_to trip_path(trip), html_options: {class:"caption"} do %>
        <h4><strong><%= trip.city[0..20] %></strong></h4>
        <h4><%= trip.country[0..20] %></h4>
        <h4><%= l(trip.start_date) %> to <%= l(trip.end_date) %></h4>
        <p class="lead">
          <%= trip.total_by_user(current_user).format %>
          <br>
          <strong>
            <%= trip.calc_in_exchange_currency(trip.total_by_user(current_user).cents).format %>
          </strong>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/_trip_info.html.erb
<div class="row">
  <div class="page-header">
    <div class="col-md-5">
      <h1><%= trip.city %> <small><%= trip.country %></small></h1>
    </div>
    <div class="col-md-4">
      <h1><small><%= l(trip.start_date) %> to <%= l(trip.end_date) %> <small>(<%= trip.amount_of_days %> days)</small></small></small></h1>
    </div>
    <div class="col-md-3 text-right">
      <br>
      <%= render partial: 'edit_trip', locals: { trip: trip} %>
      <%= link_to trip_path(trip), method: :delete, data: {confirm: "Are you sure you want to DELETE this trip?"}, class:'btn btn-danger' do %>
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class='col-md-12'>
      <div class="col-md-5">
        <h3>Travelers: <small><%= trip.users.map(&:email).join(', ') %></small></h3>
      </div>
      <div class="col-md-4">
        <h3>Local Currency: <small><%= "#{trip.local_currency.iso_code} - #{trip.local_currency.name} - #{trip.local_currency.symbol}" %></small></h3>
      </div>
      <div class="col-md-3 text-right">
        <% if current_user.currency.present? %>
          <% if trip.exchange_rate > 0.to_money %>
            <h3><small><%= "#{trip.local_currency.try(:smallest_denomination)} #{trip.currency} = #{trip.exchange_rate} #{trip.exchange_rate_currency}"%> (<%= render partial: 'add_exchange_rate', locals: {trip: trip, link_name: 'change'} %>)</small><h3>
          <% else %>
            <h3><small><%= render partial: 'add_exchange_rate', locals: {trip: trip, link_name: "add exchange rate #{trip.currency} to #{current_user.currency}"} %></small></h3>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/trips/_trip_summary.html.erb
<div class="row">
  <div class="col-md-6">
    <table class="table">
      <thead>
        <th></th>
        <th><small>Local Currency (<%= trip.currency %>)</small></th>
        <th><small>Exchange Currency (<%= trip.exchange_rate_currency %>)</small></th>
      </thead>
      <tbody>
        <tr>
          <td>Total Spent</td>
          <td><%= trip.total_by_user(current_user).format %></td>
          <td><%= trip.calc_in_exchange_currency(trip.total_by_user(current_user).cents).format %></td>
        </tr>
        <tr>
          <td>Total Spent Today</td>
          <td><%= trip.current_day_by_user(current_user).format %></td>
          <td><%= trip.calc_in_exchange_currency(trip.current_day_by_user(current_user).cents).format %></td>
        </tr>
        <tr>
          <td>Average per Day</td>
          <td><%= trip.average_per_day_by_user(current_user).format %></td>
          <td><%= trip.calc_in_exchange_currency(trip.average_per_day_by_user(current_user).cents).format %></td>
        </tr>
        <tr>
          <td>Average per Week (7 days)</td>
          <td><%= trip.average_per_week_by_user(current_user).format %></td>
          <td><%= trip.calc_in_exchange_currency(trip.average_per_week_by_user(current_user).cents).format %>  </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-md-6">
    <table class="table">
      <thead>
        <th></th>
        <th><small>Local Currency (<%= trip.currency %>)</small></th>
        <th><small>Exchange Currency (<%= trip.exchange_rate_currency %>)</small></th>
      </thead>
      <tr>
        <td>Current Week</td>
        <td><%= trip.current_week_by_user(current_user).format %></td>
        <td><%= trip.calc_in_exchange_currency(trip.current_week_by_user(current_user).cents).format %></td>
      </tr>
      <tr>
        <td>Total Debt</td>
        <td><%= sum_debts_total_amount(Debt.by_user(current_user).by_trip(trip), trip.currency).format %></td>
        <td><%= trip.calc_in_exchange_currency(sum_debts_total_amount(Debt.by_user(current_user).by_trip(trip), trip.currency).cents).format %></td>
      </tr>
      <tr>
        <td>Total Credit (Paid for)</td>
        <td><%= sum_debts_total_amount(Debt.by_recipient(current_user).by_trip(trip), trip.currency).format %></td>
        <td><%= trip.calc_in_exchange_currency(sum_debts_total_amount(Debt.by_recipient(current_user).by_trip(trip), trip.currency).cents).format %></td>
      </tr>
    </table>
  </div>
</div>

app/views/trips/index.html.erb
<%= render 'trips/add_trip' %>
<br>
<div class="row">
  <% if @trips.present? %>
    <%= render(@trips) %>
  <% else %>
    <div class="col-md-12">
      <p class='alert alert-info'><%= "Click on the button with the plus icon above to add your first trip." %></p>
    </div>
  <% end %>
</div>

app/views/trips/show.html.erb
<div class="row">
  <div class="col-md-4 pull-right text-right">
    <%= form_for :invite, url: trip_invites_path(@trip), method: :post, html: {class: 'form-inline'} do |invite_form| %>
      <div class="form-group">
        <%= invite_form.text_field :email, placeholder: 'Email', class: 'form-control' %>
      </div>
      <%= button_tag(type: 'submit', class: "btn btn-success") do %>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add travel partner
      <% end %>
    <% end %>
  </div>
</div>
<%= render partial: 'trip_info', locals: {trip: @trip} %>
<br>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New Expense</h3>
  </div>
  <div class="panel-body">
    <%= render partial: 'add_expense', locals: {trip: @trip} %>
  </div>
</div>

<div>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#summary" aria-controls="summary" role="tab" data-toggle="tab">Summary</a></li>
    <li role="presentation"><a href="#all_expenses" aria-controls="all_expenses" role="tab" data-toggle="tab">All Expenses</a></li>
    <li role="presentation"><a href="#debts" aria-controls="debts" role="tab" data-toggle="tab">Debts and Paid for</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="summary">
      <div class="panel-body">
        <%= render partial: 'trip_summary', locals: {trip: @trip} %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="all_expenses">
      <div class="panel-body">
        <%= render partial: 'expenses_table', locals: { trip: @trip, expenses: @expenses } %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="debts">
      <div class="panel-body">
        <%= render partial: 'debts/debts_and_paid_for_table', locals: {trip: @trip} %>
      </div>
    </div>
  </div>
</div>