config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  get 'trips' => 'trips#index', as: :user_root
  resources :blog_posts, only: [:index]
  resources :trips do
    resources :expenses do
      resources :debts, only: [:create]
    end
    resources :debts, only: [:index]
    resources :invites, only: [:create]
  end

  resources :cities, only: [:index]
  resources :currencies, only: [:index]

end

app/models/debt.rb
class Debt < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipient, class_name: 'User', foreign_key: :recipient_id
  belongs_to :expense

  validates :user, :recipient, :expense, presence: true

  monetize :amount_cents, with_model_currency: :currency

  scope :by_recipient_id, -> (user_recipient_id) { where(recipient_id: user_recipient_id) }
  scope :by_recipient, -> (user_recipient) { by_recipient_id(user_recipient.id) }
  scope :by_user_id, -> (specific_user_id) { where(user_id: specific_user_id) }
  scope :by_user, -> (specific_user) { by_user_id(specific_user.id) }
  scope :by_trip, -> (trip) { includes(:expense).where('expenses.trip_id = ?', trip.id).references(:expenses) }

  delegate :currency, to: :expense
  delegate :description, :created_at, to: :expense, prefix: true, allow_nil: true
end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController
  before_action :authenticate_user!

  def index
    @trip = find_trip
    @debts = current_user.debts.by_trip(@trip)
    @credits = current_user.credits.by_trip(@trip)

    if params[:user_id]
      @user = User.find(params[:user_id])
      @debts = @debts.by_recipient(@user)
      @credits = @credits.by_user(@user)
    end
  end

  def create
    debt = build_debt

    if debt.save
      flash[:notice] = 'Debt created!'
    else
      flash[:alert] = debt.errors.full_messages
    end

    redirect_to debt.expense.trip
  end

  private
  def build_debt
    expense = find_expense
    debt = expense.debts.build(debt_params)
    debt.amount = debt_params[:amount]
    debt
  end

  def find_expense
    current_user.expenses.find(params[:expense_id])
  end

  def find_trip
    current_user.trips.find(params[:trip_id])
  end

  def debt_params
    params.require(:debt).permit(:user_id, :recipient_id, :amount, :paid, :amount_currency)
  end
end

app/helpers/debts_helper.rb
module DebtsHelper

  def debt_amount_by(current_user, trip, user)
    sum_debts_total_amount(current_user.debts.by_trip(trip).by_recipient(user), trip.currency)
  end

  def credit_amount_by(current_user, trip, user)
    sum_debts_total_amount(user.debts.by_trip(trip).by_recipient(current_user), trip.currency)
  end

  def sum_debts_total_amount(debts, currency)
    debts.inject(Money.new(0, currency)) { |sum, debt| sum + debt.amount }
  end
end

app/views/debts/_add_paid_for.html.erb
<%= link_to "#", class: 'btn btn-default btn-sm', 'data-toggle'=>'modal', 'data-target'=>"#addPaidToModal_#{expense.id}" do %>
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
  <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <strong>PAID FOR</strong>
<% end %>

<!-- Modal -->
<div class="modal fade" id=<%="addPaidToModal_#{expense.id}"%> tabindex="-1" role="dialog" aria-labelledby="addPaidToModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="addPaidToModalLabel">Paid to</h4>
      </div>
      <div class="modal-body">
        <%= form_for :debt, url: trip_expense_debts_path(trip_id: trip.id, expense_id: expense.id), method: :post do |debt_form| %>
          <div class="row">
            <%= debt_form.hidden_field :recipient_id, value: current_user.id %>
            <%= debt_form.hidden_field :amount_currency, value: trip.currency %>
            <div class="form-group col-md-12">
              <%= debt_form.collection_select :user_id, (trip.users - [current_user]), :id, :email, {prompt: 'Select User'}, {id: 'select_user', class: "form-control"} %>
            </div>
            <div class="form-group col-md-12">
              <%= debt_form.label :amount %>
              <div class="input-group">
                <div class="input-group-addon"><%= trip.local_currency.symbol %></div>
                <%= debt_form.text_field :amount, class: "form-control mask-money" %>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= debt_form.submit "Create", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/debts/_debts_and_paid_for_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Paid for / Owe to</th>
      <th>Credit amount (Paid for)</th>
      <th>Debt amount </th>
      <th>Total (Credit - Debt)</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% (trip.users - [current_user]).each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= credit_amount_by(current_user, trip, user).format %></td>
        <td><%= debt_amount_by(current_user, trip, user).format %></td>
        <% total_debts = (credit_amount_by(current_user, trip, user) - debt_amount_by(current_user, trip, user)) %>
        <td><%= "#{total_debts.format} (#{trip.calc_in_exchange_currency(total_debts.cents).format})" %></td>
        <td>
          <%= link_to trip_debts_path(trip, user_id: user.id), class: 'btn btn-default btn-sm' do %>
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Details
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/debts/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'My Trips', trips_path %></li>
  <li><%= link_to @trip.city, trip_path(@trip) %></a></li>
  <li class="active">Debts and Paid for</li>
</ol>

<div class="page-header">
  <h1>Debts and Paid for</h1>
</div>

<div class="row">
  <div class='col-md-12'>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Paid for <br><small>You paid for <%= @user %></small></h3>
      </div>
      <div class="panel-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Expense Date</th>
              <th>Expense Amount</th>
              <th>Credit Amount</th>
              <th>Expense Description</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @credits.order(:created_at).each do |credit| %>
              <tr>
                <td><%= l(credit.expense.created_at.to_date) %></td>
                <td><%= credit.expense.amount.format %></td>
                <td><%= credit.amount.format %></td>
                <td><%= credit.expense_description %></td>
                <td></td>
              </tr>
            <% end %>
            <tr>
              <th></th>
              <th></th>
              <th>Total Credit Amount</th>
              <th></th>
              <th></th>
            </tr>
            <tr class="warning">
              <td></td>
              <td></td>
              <td><%= credit_amount_by(current_user, @trip, @user).format %></td>
              <td></td>
              <td></td>
            </tr>
            <tr class="info">
              <td></td>
              <td></td>
              <td><%= @trip.calc_in_exchange_currency(credit_amount_by(current_user, @trip, @user).cents).format %></td>
              <td></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class='col-md-12'>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Debts <br><small>You owe to <%= @user %></small></h3>
      </div>
      <div class="panel-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Expense Date</th>
              <th>Expense Amount</th>
              <th>Debt Amount</th>
              <th>Expense Description</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @debts.order(:created_at).each do |debt| %>
              <tr>
                <td><%= l(debt.expense.created_at.to_date) %></td>
                <td><%= debt.expense.amount.format %></td>
                <td><%= debt.amount.format %></td>
                <td><%= debt.expense_description %></td>
                <td></td>
              </tr>
            <% end %>
            <tr>
              <th></th>
              <th></th>
              <th>Total Debt Amount</th>
              <th></th>
              <th></th>
            </tr>
            <tr class="warning">
              <td></td>
              <td></td>
              <td><%= debt_amount_by(current_user, @trip, @user).format %></td>
              <td></td>
              <td></td>
            </tr>
            <tr class="info">
              <td></td>
              <td></td>
              <td><%= @trip.calc_in_exchange_currency(debt_amount_by(current_user, @trip, @user).cents).format %></td>
              <td></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>