config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  get 'trips' => 'trips#index', as: :user_root
  resources :blog_posts, only: [:index]
  resources :trips do
    resources :expenses do
      resources :debts, only: [:create]
    end
    resources :debts, only: [:index]
    resources :invites, only: [:create]
  end

  resources :cities, only: [:index]
  resources :currencies, only: [:index]

end

app/views/layouts/_favicon.html.erb
<%= favicon_link_tag 'favicon/' %>
<%= favicon_link_tag 'favicon/16.png', rel: 'icon', type: 'image/png', sizes: "16x16" %>
<%= favicon_link_tag 'favicon/24.png', rel: 'icon', type: 'image/png', sizes: "24x24" %>
<%= favicon_link_tag 'favicon/32.png', rel: 'icon', type: 'image/png', sizes: "32x32" %>
<%= favicon_link_tag 'favicon/48.png', rel: 'apple-touch-icon', type: 'image/png', sizes: "48x48" %>
<%= favicon_link_tag 'favicon/57.png', rel: 'apple-touch-icon', type: 'image/png', sizes: "57x57" %>
<%= favicon_link_tag 'favicon/64.png', rel: 'apple-touch-icon', type: 'image/png', sizes: "64x64" %>
<%= favicon_link_tag 'favicon/72.png', rel: 'apple-touch-icon', type: 'image/png', sizes: "72x72" %>
<%= favicon_link_tag 'favicon/114.png', rel: 'apple-touch-icon', type: 'image/png', sizes: "114x114" %>
<%= favicon_link_tag 'favicon/120.png', rel: 'apple-touch-icon', type: 'image/png', sizes: "120x120" %>
<%= favicon_link_tag 'favicon/144.png', rel: 'apple-touch-icon', type: 'image/png', sizes: "144x144" %>
<%= favicon_link_tag 'favicon/152.png', rel: 'apple-touch-icon', type: 'image/png', sizes: "152x152" %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small class="text-center">
    <p>
      <span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span> 2016 TravelBudget. All rights reserved. Created by <%= link_to 'rmonteiro.me', 'http://www.rmonteiro.me/' %>.
    </p>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <% brand_url = user_signed_in? ? trips_path : root_url %>
        <%= link_to "TravelBudget", brand_url, class: "logo" %>

        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right pull-right">
          <li><%= link_to 'Travel tips', blog_posts_path, class: 'link' %></li>
          <% if user_signed_in? %>
            <li><%= link_to current_user, edit_user_registration_path, class: "link" %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "link" %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path, class: "link" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/favicon' %>
    <title>TravelBudget - Keep track of your expenses while travelling</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= flash_messages %>
    <%= render 'layouts/header' %>
    <main class="container">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>